# Generated by Django 3.0.8 on 2021-01-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imtinan', '0002_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='intro',
            field=models.TextField(max_length=1000),
        ),
    ]
