# Generated by Django 3.0.8 on 2021-01-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imtinan', '0003_auto_20210105_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=100)),
                ('github', models.URLField(max_length=500)),
                ('linkedin', models.URLField(max_length=500)),
                ('insta', models.URLField(max_length=500)),
                ('fb', models.URLField(max_length=500)),
            ],
        ),
    ]
