# Generated by Django 3.0.8 on 2021-01-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imtinan', '0006_auto_20210106_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='portfolio/images')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
    ]
