# Generated by Django 3.0.8 on 2021-01-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imtinan', '0007_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='portfolio/blog/images'),
        ),
    ]
