# Generated by Django 3.0.8 on 2021-05-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imtinan', '0010_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
