# Generated by Django 3.0.8 on 2021-05-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imtinan', '0011_auto_20210506_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/blog/images')),
                ('caption', models.CharField(max_length=100)),
            ],
        ),
    ]
